# Generated by Django 4.1.6 on 2023-04-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_vegeterian',
            field=models.BooleanField(default=False),
        ),
    ]
