# Generated by Django 4.2 on 2023-04-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('dishes', models.ManyToManyField(through='items.Item', to='items.dish')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('is_delivered', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.cart')),
            ],
        ),
    ]
